# fly.toml app configuration file generated for nexus-crimson-sea-2293 on 2024-09-17T19:35:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nexus-crimson-sea-2293'
primary_region = 'waw'
kill_signal = 'SIGTERM'

[build]

[env]
  PHX_HOST = 'nexus-crimson-sea-2293.fly.dev'
  PORT = '8080'
  FLY_IO = 'true'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2
