apiVersion: v1
kind: Service
metadata:
  name: broadcaster-headless
spec:
  selector:
    app: broadcaster
  type: ClusterIP
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: broadcaster-external
spec:
  selector:
    app: broadcaster
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 4000
      protocol: TCP
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      containers:
        - name: broadcaster
          image: ghcr.io/elixir-webrtc/apps/broadcaster:latest
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DISTRIBUTION_MODE
              value: k8s
            - name: K8S_SERVICE_NAME
              value: broadcaster-headless
            - name: ICE_SERVER_URL
              value: turn:turn.example.org:3478?transport=udp
            - name: ICE_SERVER_USERNAME
              value: user-1
            - name: ICE_SERVER_CREDENTIAL
              value: pass-1
            - name: ICE_TRANSPORT_POLICY
              value: relay
            - name: ICE_PORT_RANGE
              value: 51000-52000
            - name: SECRET_KEY_BASE
              value: u1gYGbDNgA5RwdKGFe9CdK+5qLCVROAHZAFPgUVlcmjTEGdvpXqgYW9qFjLQvxZO
            - name: PHX_HOST
              value: example.org
            - name: ADMIN_USERNAME
              value: admin
            - name: ADMIN_PASSWORD
              value: admin
            - name: WHIP_TOKEN
              value: token
