name: Recognizer CI

on: 
  push:
    paths:
      - 'recognizer/**'
      - '.github/workflows/**'

permissions:
  contents: read

jobs:
  build_check_recognizer:
    name: Build and check Recognizer
    uses: ./.github/workflows/__CI__build-check-app.yml
    with:
      workdir: recognizer
      with-ffmpeg: true
